drop table position, employee,project,customer,employee_project;

create table Position
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    position_name varchar(200) NOT NULL,
    department    varchar(200) NOT NULL
);

create table Employee
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_name   varchar(100) NOT NULL,
    age         int CHECK ( age > 0 AND age < 100),
    position_id int REFERENCES Position (id) ON DELETE CASCADE
);

create table Project
(
    id           int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name varchar(200) NOT NULL UNIQUE,
    cost         int CHECK ( cost > 0 ),
    customer_id  int REFERENCES Customer (id) ON DELETE CASCADE
);

create table Employee_Project
(
    employee_id int REFERENCES Employee (id),
    project_id  int REFERENCES Project (id),
    PRIMARY KEY (employee_id, project_id)
);

create table Customer
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_name varchar(100) NOT NULL,
    email         varchar(100) NOT NULL UNIQUE
);